Syslog                  yes
RequiredHeaders         yes
UMask                   002
OversignHeaders         From
Background              yes
PidFile                 /run/opendkim/opendkim.pid

# Jalur komunikasi lokal
Socket                  inet:8891@localhost

# Pemetaan Kunci Domain
KeyTable                refile:/etc/opendkim/key.table
SigningTable            refile:/etc/opendkim/signing.table
ExternalIgnoreList      refile:/etc/opendkim/trusted.hosts
InternalHosts           refile:/etc/opendkim/trusted.hosts

# Nonaktifkan pemeriksaan ketat keamanan kunci untuk menghindari error kepemilikan uid
RequireSafeKeys         false

# Tentukan user pengidentifikasi agar OpenDKIM berjalan sebagai user opendkim
UserID                  opendkim

