export type AuditEventName = 
  | 'INVOICE_CREATED' | 'INVOICE_UPDATED' | 'INVOICE_ADJUSTED'
  | 'PAYMENT_RECEIVED' | 'PAYMENT_VERIFIED' | 'PAYMENT_REFUND'
  | 'ACCOUNT_SUSPENDED' | 'ACCOUNT_REACTIVATED'
  | 'OVERPAYMENT_DETECTED' | 'WRITE_OFF_APPROVED'
  | 'TICKET_CREATED' | 'TICKET_ASSIGNED' | 'TICKET_ESCALATED' | 'TICKET_CLOSED' | 'TICKET_REOPENED'
  | 'PACKAGE_CREATED' | 'PACKAGE_UPDATED' | 'PACKAGE_ACTIVATED' | 'PACKAGE_DEACTIVATED'
  | 'CUSTOMER_CREATED' | 'CUSTOMER_UPDATED' | 'CUSTOMER_DELETED'
  | 'ROLE_PERMISSIONS_MODIFIED' | 'USER_ACCESS_REVOKED'
  | 'TEMPLATE_UPDATED' | 'MASS_BROADCAST_TRIGGERED';
