const AUDIT_EVENTS = {
  CUSTOMER_CREATED: 'CUSTOMER_CREATED',
  CUSTOMER_UPDATED: 'CUSTOMER_UPDATED',
  PAYMENT_RECEIVED: 'PAYMENT_RECEIVED',
  SYSTEM_LOGIN: 'SYSTEM_LOGIN',
  DATA_EXPORTED: 'DATA_EXPORTED'
};

module.exports = { AUDIT_EVENTS };
