server {
    listen 80;
    server_name topclass.id www.topclass.id;

    # Serve Static Frontend Next.js / HTML Files
    location / {
        root /usr/share/nginx/html;
        index index.html;
        # Mendukung Next.js static export (.html routing)
        try_files $uri $uri.html $uri/ /index.html;
    }

    # Proxy ke Node.js Backend
    location /api/ {
        proxy_pass http://backend:3000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }
}
